// A selection of 1000 common English words
export const WORDS = [
  "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", "that", "for", "they", "with", "as", "not", "on", "she", "at", "by",
  "this", "we", "you", "do", "but", "from", "or", "which", "one", "would", "all", "will", "there", "say", "who", "make", "when", "can",
  "more", "if", "no", "man", "out", "other", "so", "what", "time", "up", "go", "about", "than", "into", "could", "state", "only",
  "new", "year", "some", "take", "come", "these", "know", "see", "use", "get", "like", "then", "first", "any", "work", "now", "may",
  "such", "give", "over", "think", "most", "even", "find", "day", "also", "after", "way", "many", "must", "look", "before", "great",
  "back", "through", "long", "where", "much", "should", "well", "people", "down", "own", "just", "because", "good", "each", "those",
  "feel", "seem", "how", "high", "too", "place", "little", "world", "very", "still", "nation", "hand", "old", "life", "tell", "write",
  "become", "here", "show", "house", "both", "between", "need", "mean", "call", "develop", "under", "last", "right", "move", "thing",
  "general", "school", "never", "same", "another", "begin", "while", "number", "part", "turn", "real", "leave", "might", "want",
  "point", "form", "off", "child", "few", "small", "since", "against", "ask", "late", "home", "interest", "large", "person", "end",
  "open", "public", "follow", "during", "present", "without", "again", "hold", "govern", "around", "possible", "head", "consider",
  "word", "program", "problem", "however", "lead", "system", "set", "order", "eye", "plan", "run", "keep", "face", "fact", "group",
  "play", "stand", "increase", "early", "course", "change", "help", "line", "city", "put", "close", "case", "force", "meet", "once",
  "water", "upon", "war", "build", "hear", "light", "unite", "live", "every", "country", "bring", "center", "let", "side", "try",
  "provide", "continue", "away", "political", "require", "sit", "information", "lose", "pay", "meet", "include", "believe", "allow",
  "lead", "service", "government", "company", "important", "always", "story", "member", "become", "within", "start", "train", "air",
  "power", "business", "issue", "market", "art", "far", "idea", "law", "minute", "month", "result", "role", "student", "view", "walk",
  "area", "body", "book", "car", "community", "death", "door", "education", "effect", "father", "foot", "friend", "girl", "guy",
  "health", "history", "hour", "job", "kind", "level", "major", "moment", "money", "morning", "mother", "music", "name", "news",
  "night", "office", "parent", "party", "period", "policy", "process", "question", "reason", "research", "room", "sense", "social",
  "son", "sound", "study", "team", "teacher", "today", "tongue", "town", "type", "value", "voice", "war", "way", "week", "woman",
  "yesterday", "able", "bad", "best", "better", "big", "black", "certain", "clear", "different", "early", "easy", "economic",
  "federal", "final", "fine", "foreign", "free", "full", "global", "great", "green", "hard", "high", "human", "important",
  "international", "large", "late", "left", "legal", "light", "local", "long", "low", "main", "major", "military", "national",
  "new", "old", "only", "other", "past", "personal", "political", "poor", "private", "public", "real", "recent", "red", "right",
  "short", "single", "small", "social", "special", "strong", "sure", "true", "white", "whole", "young", "accept", "achieve", "act",
  "add", "admit", "affect", "afford", "agree", "aim", "allow", "answer", "appear", "apply", "argue", "arrange", "arrive", "ask",
  "attack", "avoid", "base", "beat", "become", "begin", "believe", "belong", "break", "build", "burn", "buy", "call", "can",
  "care", "carry", "catch", "cause", "change", "charge", "check", "choose", "claim", "clean", "clear", "climb", "close", "collect",
  "come", "commit", "compare", "complain", "complete", "concern", "confirm", "connect", "consider", "consist", "contact",
  "contain", "continue", "contribute", "control", "cook", "copy", "correct", "cost", "count", "cover", "create", "cross", "cry",
  "cut", "damage", "dance", "deal", "decide", "deliver", "demand", "deny", "depend", "describe", "design", "destroy", "develop",
  "die", "disappear", "discover", "discuss", "divide", "do", "draw", "dream", "drive", "drink", "drop", "eat", "encourage", "end",
  "enjoy", "examine", "exist", "expect", "experience", "explain", "express", "extend", "face", "fail", "fall", "fasten", "feed",
  "feel", "fight", "fill", "find", "finish", "fit", "fly", "fold", "follow", "force", "forget", "forgive", "form", "found", "gain",
  "get", "give", "go", "grow", "handle", "happen", "hate", "have", "head", "hear", "help", "hide", "hit", "hold", "hope", "hurt",
  "identify", "imagine", "improve", "include", "increase", "indicate", "influence", "inform", "intend", "introduce", "invite",
  "involve", "join", "jump", "keep", "kick", "kill", "kiss", "knock", "know", "last", "laugh", "lay", "lead", "learn", "leave",
  "lend", "let", "lie", "like", "link", "listen", "live", "look", "lose", "love", "make", "manage", "mark", "matter", "may", "mean",
  "measure", "meet", "mention", "mind", "miss", "move", "need", "notice", "obtain", "occur", "offer", "open", "order", "owe",
  "own", "pack", "pass", "pay", "perform", "permit", "phone", "place", "plan", "play", "point", "prefer", "prepare", "present",
  "press", "prevent", "produce", "promise", "protect", "prove", "provide", "publish", "pull", "push", "put", "raise", "reach",
  "read", "realize", "receive", "recognize", "record", "reduce", "refer", "reflect", "refuse", "regard", "relate", "release",
  "remain", "remember", "remove", "repeat", "replace", "reply", "report", "represent", "require", "rest", "result", "return",
  "reveal", "ring", "rise", "roll", "run", "save", "say", "see", "seem", "sell", "send", "separate", "serve", "set", "settle",
  "shake", "shall", "share", "shine", "shoot", "shout", "show", "shut", "sign", "sing", "sit", "sleep", "smile", "sort", "sound",
  "speak", "stand", "start", "state", "stay", "steal", "stick", "stop", "strike", "study", "succeed", "suffer", "suggest", "suit",
  "supply", "support", "suppose", "survive", "take", "talk", "teach", "tear", "tell", "tend", "test", "thank", "think", "throw",
  "tie", "touch", "train", "travel", "treat", "try", "turn", "understand", "use", "used", "visit", "vote", "wait", "walk", "want",
  "warn", "wash", "watch", "wear", "win", "wish", "wonder", "work", "worry", "would", "write", "wrong", "above", "across",
  "action", "actor", "actress", "address", "adult", "advice", "afternoon", "age", "agent", "agreement", "ahead", "aid", "aim",
  "airport", "alarm", "album", "alcohol", "alternative", "amazing", "ambition", "amount", "analysis", "analyst", "animal",
  "another", "answer", "anxiety", "anybody", "anyone", "anything", "anyway", "anywhere", "apartment", "apple", "application",
  "appointment", "approach", "april", "argument", "arm", "army", "around", "arrival", "article", "artist", "aside", "aspect",
  "assessment", "assignment", "assistant", "association", "assumption", "atmosphere", "attack", "attempt", "attention",
  "attitude", "audience", "august", "aunt", "author", "authority", "autumn", "average", "award", "away", "awful", "baby",
  "background", "bacon", "badly", "bag", "bake", "balance", "ball", "band", "bank", "bar", "barrier", "base", "baseball",
  "basic", "basically", "basket", "basketball", "bath", "bathroom", "battery", "battle", "beach", "bean", "bear", "beautiful",
  "beauty", "bed", "bedroom", "bee", "beef", "beer", "before", "beginning", "behavior", "behind", "belief", "bell", "below",
  "belt", "bench", "bend", "beneath", "benefit", "beside", "besides", "bet", "beyond", "bicycle", "bid", "bike", "bill", "bin",
  "bird", "birth", "birthday", "biscuit", "bit", "bite", "bitter", "blame", "blank", "blanket", "blind", "block", "blond",
  "blood", "blow", "blue", "board", "boat", "boil", "bomb", "bone", "bonus", "booking", "boot", "border", "bored", "boring",
  "born", "boss", "bother", "bottle", "bottom", "bowl", "box", "brain", "branch", "brand", "brave", "bread", "break",
  "breakfast", "breast", "breath", "breathe", "brick", "bridge", "brief", "bright", "brilliant", "bring", "broad",
  "brother", "brown", "brush", "bubble", "budget", "bug", "building", "bunch", "burn", "bury", "bus", "bush", "business",
  "businessman", "busy", "butter", "button", "by", "bye", "cabinet", "cable", "cafe", "cake", "calculation", "camera", "camp",
  "campaign", "campus", "can", "cancel", "cancer", "candidate", "candy", "cap", "capability", "capacity", "capital", "captain",
  "capture", "card", "career", "careful", "carefully", "carpet", "carrot", "cartoon", "case", "cash", "cast", "castle", "cat",
  "catch", "category", "cause", "celebrate", "celebration", "celebrity", "cell", "cent", "central", "centre", "century",
  "ceremony", "certainly", "chain", "chair", "chairman", "challenge", "champion", "championship", "chance", "change",
  "channel", "chapter", "character", "characteristic", "charge", "charity", "chart", "chase", "chat", "cheap", "check",
  "cheek", "cheese", "chef", "chemical", "chemistry", "chest", "chicken", "chief", "childhood", "chip", "chocolate",
  "choice", "choose", "church", "cigarette", "cinema", "circle", "circumstance", "citizen", "civil", "classic", "classical",
  "classroom", "clean", "clerk", "click", "client", "climate", "climb", "clock", "close", "closely", "closet", "cloth",
  "clothes", "cloud", "club", "clue", "coach", "coal", "coast", "coat", "code", "coffee", "coin", "cold", "collar",
  "colleague", "collect", "collection", "college", "color", "column", "combination", "combine", "comedy", "comfort",
  "comfortable", "command", "comment", "commercial", "commission", "commitment", "committee", "common", "communicate",
  "communication", "community", "comparison", "competition", "competitive", "complain", "complaint", "complete",
  "completely", "complex", "component", "computer", "concentrate", "concentration", "concept", "concern", "concert",
  "conclude", "conclusion", "condition", "conduct", "conference", "confidence", "confident", "confirm", "conflict",
  "confuse", "connect", "connection", "conscious", "consequence", "conservative", "consider", "consideration", "consist",
  "consistent", "constant", "constantly", "construct", "construction", "consultant", "consumer", "contact", "contain",
  "container", "contemporary", "content", "contest", "context", "continue", "continuous", "contract", "contrast", "contribute",
  "contribution", "control", "conversation", "convert", "convince", "cook", "cookie", "cooking", "cool", "cooperation", "copy",
  "core", "corner", "corporate", "correct", "correctly", "cost", "costume", "cottage", "cotton", "could", "council", "count",
  "countryside", "county", "couple", "courage", "course", "court", "cousin", "cover", "cow", "crack", "craft", "crash",
  "crazy", "cream", "create", "creation", "creative", "creature", "credit", "crew", "crime", "criminal", "crisis", "criterion",
  "critic", "critical", "criticism", "criticize", "crop", "cross", "crowd", "crucial", "cry", "cultural", "culture", "cup",
  "cupboard", "cure", "currently", "curtain", "curve", "custom", "customer", "cycle", "dad", "daily", "damage", "dance",
  "danger", "dangerous", "dark", "data", "date", "daughter", "dead", "deal", "dear", "debate", "debt", "decade", "december",
  "decent", "decide", "decision", "declare", "decline", "deep", "defeat", "defend", "defendant", "defense", "define",
  "definitely", "definition", "degree", "delay", "delete", "delight", "deliver", "delivery", "demand", "demonstrate",
  "dentist", "department", "departure", "depend", "deposit", "depressed", "depth", "derive", "describe", "description",
  "desert", "deserve", "design", "designer", "desire", "desk", "desperate", "despite", "destroy", "detail", "detailed",
  "detect", "determine", "develop", "development", "device", "devil", "diagram", "diamond", "diary", "die", "diet", "differ",
  "difference", "different", "difficult", "difficulty", "dig", "digital", "dinner", "direct", "direction", "directly",
  "director", "dirt", "dirty", "disability", "disadvantage", "disagree", "disappear", "disappointed", "disaster", "disc",
  "discipline", "discount", "discover", "discovery", "discuss", "discussion", "disease", "dish", "disk", "dislike", "dismiss",
  "display", "distance", "distribute", "distribution", "district", "divide", "division", "divorce", "doctor", "document",
  "documentary", "dog", "dollar", "domain", "domestic", "dominate", "donate", "door", "dot", "double", "doubt", "down",
  "download", "downtown", "downward", "dozen", "draft", "drag", "drama", "dramatic", "draw", "drawing", "dream", "dress",
  "drink", "drive", "driver", "drop", "drug", "drum", "drunk", "dry", "due", "dull", "during", "dust", "duty", "DVD", "each",
  "ear", "early", "earn", "earth", "ease", "easily", "east", "eastern", "easy", "eat", "economic", "economics", "economy",
  "edge", "edit", "edition", "editor", "educate", "education", "educational", "effect", "effective", "effectively",
  "efficiency", "efficient", "effort", "egg", "either", "elbow", "elect", "election", "electric", "electrical",
  "electricity", "electronic", "element", "elevator", "else", "elsewhere", "email", "embarrassed", "emerge", "emergency",
  "emotion", "emotional", "emphasis", "emphasize", "empire", "employ", "employee", "employer", "employment", "empty",
  "enable", "encounter", "encourage", "end", "enemy", "energy", "engage", "engine", "engineer", "engineering", "enhance",
  "enjoy", "enormous", "enough", "enquiry", "ensure", "enter", "enterprise", "entertainment", "enthusiasm", "entire",
  "entirely", "entitle", "entrance", "entry", "environment", "environmental", "episode", "equal", "equally", "equipment",
  "error", "escape", "especially", "essay", "essential", "establish", "estate", "estimate", "etc", "ethical", "euro",
  "evaluate", "even", "evening", "event", "eventually", "ever", "every", "everybody", "everyday", "everyone", "everything",
  "everywhere", "evidence", "evil", "exact", "exactly", "exam", "examination", "examine", "example", "excellent", "except",
  "exchange", "excited", "excitement", "exciting", "excuse", "executive", "exercise", "exhibit", "exhibition", "exist",
  "existence", "existing", "exit", "expand", "expect", "expectation", "expenditure", "expense", "expensive", "experience",
  "experiment", "expert", "explain", "explanation", "explode", "exploration", "explore", "explosion", "export", "expose",
  "express", "expression", "extend", "extent", "external", "extra", "extraordinary", "extreme", "extremely", "eye", "face",
  "facility", "fact", "factor", "factory", "fail", "failure", "fair", "fairly", "faith", "fall", "false", "familiar",
  "family", "famous", "fan", "fancy", "far", "farm", "farmer", "fashion", "fast", "fat", "father", "fault", "favor",
  "favorite", "fear", "feature", "february", "federal", "fee", "feed", "feedback", "feel", "feeling", "fellow", "female",
  "fence", "festival", "fever", "few", "fiber", "fiction", "field", "fifteen", "fifth", "fifty", "fight", "fighting",
  "figure", "file", "fill", "film", "final", "finally", "finance", "financial", "find", "finding", "fine", "finger", "finish",
  "fire", "firm", "first", "firstly", "fish", "fishing", "fit", "five", "fix", "fixed", "flag", "flame", "flash", "flat",
  "flavor", "flesh", "flight", "float", "flood", "floor", "flour", "flow", "flower", "fly", "focus", "fold", "folk",
  "follow", "following", "food", "foot", "football", "for", "force", "foreign", "forest", "forever", "forget", "forgive",
  "fork", "form", "formal", "format", "formation", "former", "formula", "forth", "fortunate", "forty", "forward", "found",
  "foundation", "four", "fourth", "frame", "framework", "free", "freedom", "freeze", "frequency", "frequently", "fresh",
  "friday", "friend", "friendly", "friendship", "from", "front", "frozen", "fruit", "fry", "fuel", "full", "fully", "fun",
  "function", "fund", "fundamental", "funding", "funeral", "funny", "fur", "furniture", "further", "future", "gain", "gallery",
  "game", "gang", "gap", "garage", "garden", "gas", "gate", "gather", "gear", "gender", "gene", "general", "generally",
  "generate", "generation", "generous", "gentle", "gentleman", "gently", "geography", "get", "ghost", "giant", "gift", "girl",
  "girlfriend", "give", "glad", "glance", "glass", "global", "glove", "go", "goal", "god", "gold", "golden", "golf", "good",
  "goodbye", "govern", "government", "governor", "grab", "grade", "gradually", "graduate", "grain", "grand", "grandfather",
  "grandmother", "grandparent", "grant", "grape", "grass", "grateful", "grave", "gray", "great", "greatly", "green", "grey",
  "grocery", "ground", "group", "grow", "growth", "guarantee", "guard", "guess", "guest", "guide", "guilty", "guitar", "gun",
  "guy", "habit", "habitat", "hair", "half", "hall", "hand", "handle", "hang", "happen", "happily", "happiness", "happy",
  "hard", "hardly", "harm", "hat", "hate", "have", "he", "head", "headache", "headline", "headquarter", "health", "healthy",
  "hear", "hearing", "heart", "heat", "heating", "heaven", "heavily", "heavy", "heel", "height", "helicopter", "hell",
  "hello", "help", "helpful", "hence", "her", "here", "hero", "hers", "herself", "hesitate", "hey", "hi", "hide", "high",
  "highlight", "highly", "highway", "hill", "him", "himself", "hip", "hire", "his", "historian", "historical", "history",
  "hit", "hobby", "hockey", "hold", "hole", "holiday", "holy", "home", "homework", "honest", "honestly", "honey", "honor",
  "hook", "hope", "horizon", "horn", "horrible", "horror", "horse", "hospital", "host", "hot", "hotel", "hour", "house",
  "household", "housing", "how", "however", "huge", "human", "humor", "hundred", "hungry", "hunt", "hunting", "hurry",
  "hurt", "husband", "I", "ice", "icon", "idea", "ideal", "identify", "identity", "ie", "if", "ignore", "ill", "illegal",
  "illness", "illustrate", "image", "imagination", "imagine", "immediate", "immediately", "immigrant", "impact", "implement",
  "implication", "imply", "import", "importance", "important", "impose", "impossible", "impress", "impressed", "impression",
  "impressive", "improve", "improvement", "in", "inch", "incident", "include", "including", "income", "increase",
  "increasingly", "incredible", "incredibly", "indeed", "independent", "index", "indicate", "indication", "individual",
  "industrial", "industry", "inevitable", "infant", "infection", "inflation", "influence", "inform", "informal",
  "information", "ingredient", "initial", "initially", "initiative", "injure", "injured", "injury", "inner", "innocent",
  "innovation", "input", "inquiry", "insect", "inside", "insight", "insist", "install", "instance", "instead", "institute",
  "institution", "instruction", "instructor", "instrument", "insurance", "intellectual", "intelligence", "intelligent",
  "intend", "intended", "intense", "intention", "interaction", "interest", "interested", "interesting", "internal",
  "international", "internet", "interpret", "interpretation", "interrupt", "interview", "into", "introduce", "introduction",
  "invent", "invention", "invest", "investigate", "investigation", "investment", "invitation", "invite", "involve",
  "involved", "involvement", "iron", "island", "issue", "it", "item", "its", "itself", "jacket", "jam", "january", "jazz",
  "jeans", "jet", "jewelry", "job", "join", "joke", "journal", "journalist", "journey", "joy", "judge", "judgment", "juice",
  "july", "jump", "june", "junior", "just", "justice", "justify", "keen", "keep", "key", "keyboard", "kick", "kid", "kill",
  "killing", "kilometer", "kind", "king", "kiss", "kitchen", "knee", "knife", "knock", "know", "knowledge", "lab", "label",
  "laboratory", "labor", "lack", "ladder", "lady", "lake", "lamp", "land", "landscape", "lane", "language", "lap", "large",
  "largely", "last", "late", "lately", "later", "latest", "laugh", "laughter", "launch", "law", "lawyer", "lay", "layer",
  "lazy", "lead", "leader", "leadership", "leading", "leaf", "league", "lean", "learn", "learning", "least", "leather",
  "leave", "lecture", "left", "leg", "legacy", "legal", "legend", "leisure", "lemon", "lend", "length", "less", "lesson",
  "let", "letter", "level", "liberal", "library", "license", "lid", "lie", "life", "lifestyle", "lift", "light", "like",
  "likely", "limit", "limitation", "limited", "line", "link", "lip", "liquid", "list", "listen", "literally", "literary",
  "literature", "little", "live", "lively", "living", "load", "loan", "local", "locate", "located", "location", "lock",
  "logic", "logical", "lonely", "long", "long-term", "look", "loop", "loose", "lord", "lose", "loss", "lost", "lot", "loud",
  "loudly", "love", "lovely", "lover", "low", "lower", "loyal", "luck", "lucky", "lunch", "lung", "luxury", "machine", "mad",
  "magazine", "magic", "mail", "main", "mainly", "maintain", "maintenance", "major", "majority", "make", "makeup", "male",
  "mall", "man", "manage", "management", "manager", "manner", "manufacturer", "manufacturing", "many", "map", "march",
  "margin", "mark", "market", "marketing", "marriage", "married", "marry", "mask", "mass", "massive", "master", "match",
  "mate", "material", "math", "mathematics", "matter", "maximum", "may", "maybe", "mayor", "me", "meal", "mean", "meaning",
  "means", "meanwhile", "measure", "measurement", "meat", "mechanism", "media", "medical", "medication", "medicine", "medium",
  "meet", "meeting", "melt", "member", "membership", "memory", "mental", "mention", "menu", "mere", "merely", "mess",
  "message", "metal", "meter", "method", "middle", "midnight", "might", "mild", "mile", "military", "milk", "million",
  "mind", "mine", "minister", "minor", "minority", "minute", "miracle", "mirror", "miss", "missile", "mission", "mistake",
  "mix", "mixed", "mixture", "mobile", "modal", "model", "modern", "mom", "moment", "monday", "money", "monitor", "month",
  "monthly", "monument", "mood", "moon", "moral", "more", "moreover", "morning", "mortgage", "most", "mostly", "mother",
];

export const TIME_OPTIONS = [15, 30, 60, 120];
export const WORD_COUNT_OPTIONS = [10, 25, 50, 100];


export const KEYBOARD_LAYOUT = [
  ['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'Backspace'],
  ['Tab', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '[', ']', '\\'],
  ['CapsLock', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ';', '\'', 'Enter'],
  ['Shift', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', ',', '.', '/', 'ShiftR'],
  ['Space']
];

export const KEY_TO_EVENT_CODE: { [key: string]: string } = {
  '`': 'Backquote', '1': 'Digit1', '2': 'Digit2', '3': 'Digit3', '4': 'Digit4', '5': 'Digit5', '6': 'Digit6', '7': 'Digit7', '8': 'Digit8', '9': 'Digit9', '0': 'Digit0', '-': 'Minus', '=': 'Equal',
  'Q': 'KeyQ', 'W': 'KeyW', 'E': 'KeyE', 'R': 'KeyR', 'T': 'KeyT', 'Y': 'KeyY', 'U': 'KeyU', 'I': 'KeyI', 'O': 'KeyO', 'P': 'KeyP', '[': 'BracketLeft', ']': 'BracketRight', '\\': 'Backslash',
  'A': 'KeyA', 'S': 'KeyS', 'D': 'KeyD', 'F': 'KeyF', 'G': 'KeyG', 'H': 'KeyH', 'J': 'KeyJ', 'K': 'KeyK', 'L': 'KeyL', ';': 'Semicolon', '\'': 'Quote',
  'Z': 'KeyZ', 'X': 'KeyX', 'C': 'KeyC', 'V': 'KeyV', 'B': 'KeyB', 'N': 'KeyN', 'M': 'KeyM', ',': 'Comma', '.': 'Period', '/': 'Slash',
  'ShiftR': 'ShiftRight',
};
